# Generated by Django 5.2.1 on 2025-05-19 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationshiptype',
            name='created_at',
        ),
        migrations.AddField(
            model_name='alternative',
            name='criteria_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.relationshiptype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='main.alternative'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='main.alternative'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('source', 'target')},
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('numeric', 'Числовий'), ('text', 'Текстовий'), ('color', 'Колір')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='main.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
